FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:197 in lock_acquire(): assertion `!lock_held_by_current_thread (lock)' failed.
Call stack: 0x8004217f3b 0x800420a4a9 0x8004220ea7 0x8004220fcc 0x8004221037 0x80042213e8 0x800422131d 0x800421cda4 0x8004208fe7 0x8004209405 0x4001f3 0x400d85 0x400dce
Translation of call stack:
0x0000008004217f3b: debug_panic (lib/kernel/debug.c:32)
0x000000800420a4a9: lock_acquire (threads/synch.c:199)
0x0000008004220ea7: vm_get_victim (vm/vm.c:139)
0x0000008004220fcc: vm_evict_frame (vm/vm.c:165)
0x0000008004221037: vm_get_frame (vm/vm.c:192)
0x00000080042213e8: vm_do_claim_page (vm/vm.c:292)
0x000000800422131d: vm_try_handle_fault (vm/vm.c:257)
0x000000800421cda4: page_fault (userprog/exception.c:145)
0x0000008004208fe7: intr_handler (threads/interrupt.c:352)
0x0000008004209405: intr_entry (threads/intr-stubs.o:?)
0x00000000004001f3: (unknown)
0x0000000000400d85: (unknown)
0x0000000000400dce: (unknown)
